development:
  adapter: postgresql
  database: boletodb
  encoding: unicode
  username: postgres
  password: admin
  host: localhost
  port: 5432

production:
    adapter: postgresql
    encoding: unicode
    database: dagr6ntkr5t803
    pool: 5
    username: ppjtrauxsrkbpf
    password: chxZ6603qctlcFjCFFBhOoAzTm
